# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Rocket.Chat
# Description of the Site
description: Proyecto sobre Rocket.Chat para el curso de ASIR en el IES Gonzalo Nazareno
# URL of Image of the Site
site-image: https://github.com/ManuelLoraRoman/proyectorocketchat.github.io/blob/main/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Rocket.Chat, Slack, Communication
# URL for the Image of custom Favicon
favicon-url: https://github.com/ManuelLoraRoman/proyectorocketchat.github.io/blob/main/assets/images/favicon-16x16.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: manuelloraroman@gmail.com
facebook_username: Manu Lora Roman
twitter_username: ManuelLoraRoman
instagram_username: LoraInThePanda
linkedin_username: ManuelLoraRoman
github_username:  ManuelLoraRoman
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: ManuelLoraRoman
# URL for the Image of the Author
author-image: https://pbs.twimg.com/profile_images/924861277956173824/1x1O3l3v_400x400.jpg
# 60 Words About the Author
author-about: Administrador de Sistemas Informáticos en Red. DevOps
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ManuelLoraRoman/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
